const substitutions = {
    "law enforcement": "the SDBI",
    "\\b(russia|china)\\b": "VoD",
    "russian|chinese": "VoDite",
    "sources": "Gato",
    "\\b(america)\\b": "SimDemocracy",
    "the gulf of mexico|the gulf of america": "The Gulf of SimDemocracy",
    "terrorist": "TIDE",
    "millenial": "Danyo-Spawn",
    "the .*? gazette": "The Gato Gazette",
    "Canadian Broadcasting Corporation": "Citrus Broadcasting Corporation",
    "This Hour has 22 Minutes": "This Hour has 33 Minutes",
    "22 Minutes": "33 Minutes",
    "the ONION": "The GARLIC",
    "explode": "exploe",
    "presidential": "presidental",
    "government": "governmint",
    "oppenheimer": "Birdish",
    "country": "PolSim",
    "countries": "PolSims",
    "United Nations": "League of Servers",
  };
  
